name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run buildFrontend
        env:
          NODE_ENV: production

      - name: Upload dist/ Directory
        uses: actions/upload-artifact@v2
        with:
          name: quaesta-outputs
          path: dist/

  deploy-frontend:
    name: Deploy Frontend
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Download dist/ Directory
        uses: actions/download-artifact@v2
        with:
          name: quaesta-outputs
          path: dist

      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@v3
      #   with:
      #     gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     git-user-signingkey: true
      #     git-commit-gpgsign: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-aws-lambda:
    name: Deploy AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Quaesta .env File
        uses: DeveloperRic/action-create-env@v1.0.4
        with:
          full_text: |
            AUTH_KEY=${{ secrets.AUTH_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            DDB_ENDPOINT=${{ secrets.DDB_ENDPOINT }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            PASSWORD_KEY=${{ secrets.PASSWORD_KEY }}
            TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
            TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: Deploy
        run: npm run deployLambda
